version: '3.8'

services:
  #PostgreSQL database for the application
  eazylearn-postgres:
    image: "postgres:14.1-alpine"
    container_name: "eazylearn-postgres"
    volumes:
      - eazylearn-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Maps the exposed by Docker port 5432 on the container to the port 5432 on the host machine
    # Environment variables for PostgreSQL database
    environment:
      - POSTGRES_DB=eazylearn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  #Backend Spring Boot application
  eazylearn-spring-boot-app:
    build: .
    container_name: eazylearn-spring-boot-app

    # Environment variables for Spring Boot application
    environment:
      - DB_SERVER=eazylearn-postgres
      - POSTGRES_DB=eazylearn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "8080:8080" # Maps the exposed by Docker port 8080 on the container to the port 8080 on the host machine
    links:
      - eazylearn-postgres

# Volumes for DB data
volumes:
  eazylearn-data:
    driver: local