### JWT Authorization. Retrieve and save token.
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/x-www-form-urlencoded

email=user1&password=user1

> {% client.global.set("auth_token", response.body.access_token); %}


### Find all Users
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Bearer {{auth_token}}

### Find User by id
GET http://localhost:8080/api/v1/users/
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create User
POST http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
}

### Update User by id
PATCH http://localhost:8080/api/v1/users/2105b3c6-917a-4a8f-aca9-fd4dbcaef585
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "ilya",
  "email": "ilya500514@gmail.com",
  "password": "ilya500514"
}

### Delete User by id
DELETE http://localhost:8080/api/v1/users/277cbadd-a310-4f7d-b12e-4f68628f4dd8
Content-Type: application/json
Authorization: Bearer {{auth_token}}